spring.application.name=expenses
spring.datasource.url=jdbc:postgresql://localhost:5432/finguard
spring.datasource.username=finguard_user
spring.datasource.password=finguard_pass

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
